pipeline {
     agent any

     stages {
         stage('Checkout') {
             steps {
                 echo 'Checking out...'
                 git branch: 'main', url: 'https://github.com/maria-neto/devops-23-24-JPE-1231842.git'
             }
         }
         stage('Assemble') {
             steps {
                 echo 'Assembling...'
                 dir('CA2/Part1') {
                 sh 'chmod +x gradlew'
                 sh './gradlew clean assemble'
                 }
             }
         }
         stage('Test') {
             steps {
             echo 'Testing...'
             dir('CA2/Part1') {
                 sh './gradlew test'
             }
         }
             post {
                 always {
                     junit '**/build/test-results/**/*.xml'
                 }
             }
         }
         stage('Archive') {
             steps {
             echo 'Archiving...'
             dir('CA2/Part1') {
                 archiveArtifacts 'build/libs/*.jar'
                 }
             }
         }
     }
 }