pipeline {
     agent any

     stages {
         stage('Checkout') {
             steps {
                 echo 'Checking out...'
                 git branch: 'main', url: 'https://github.com/maria-neto/devops-23-24-JPE-1231842.git'
             }
         }
         stage('Set Permissions') {
             steps {
                 dir('CA2/part1') {
                     echo 'Setting executable permissions on gradlew...'
                     bat 'gradlew.bat'
                 }
             }
         }
         stage('Assemble') {
             steps {
                 dir('CA2/Part1') {
                     echo 'Assembling the application...'
                     bat './gradlew.bat assemble'
                 }
             }
         }
         stage('Test') {
             steps {
                 dir('CA2/Part1') {
                     echo 'Running unit tests...'
                     bat './gradlew.bat test'
                 }
             }
         }
         stage('Archive') {
             steps {
             echo 'Archiving...'
             dir('CA2/Part1') {
                 archiveArtifacts 'build/libs/*.jar'
                 }
             }
         }
     }
 }